### ISSUE TITLE
T-Heads

### ISSUE THREAD

**Issue by ArielHeleneto** [ruyisdk/support-matrix#27]
## Links

- https://github.com/ruyisdk/support-matrix/blob/549595a06779a25e9fda132f1b430e8c5463028a/M0s/README.md?plain=1#L9
- https://github.com/ruyisdk/support-matrix/blob/549595a06779a25e9fda132f1b430e8c5463028a/M0s/README_zh.md?plain=1#L9
- https://github.com/ruyisdk/support-matrix/blob/549595a06779a25e9fda132f1b430e8c5463028a/LicheePi4A/README.md?plain=1#L17
- https://github.com/ruyisdk/support-matrix/blob/549595a06779a25e9fda132f1b430e8c5463028a/LicheePi4A/README_zh.md?plain=1#L17
- https://github.com/ruyisdk/support-matrix/blob/549595a06779a25e9fda132f1b430e8c5463028a/M0s/FreeRTOS/README.md?plain=1#L8
- https://github.com/ruyisdk/support-matrix/blob/549595a06779a25e9fda132f1b430e8c5463028a/LicheeCluster4A/README_zh.md?plain=1#L23
- https://github.com/ruyisdk/support-matrix/blob/549595a06779a25e9fda132f1b430e8c5463028a/LicheeCluster4A/README.md?plain=1#L23
- https://github.com/ruyisdk/support-matrix/blob/549595a06779a25e9fda132f1b430e8c5463028a/M0P_Dock/FreeRTOS/README_zh.md?plain=1#L13
- https://github.com/ruyisdk/support-matrix/blob/549595a06779a25e9fda132f1b430e8c5463028a/LicheeCluster4A/Fedora/README_zh.md?plain=1#L8
- https://github.com/ruyisdk/support-matrix/blob/549595a06779a25e9fda132f1b430e8c5463028a/LicheePi4A/Fedora/README.md?plain=1#L8
- https://github.com/ruyisdk/support-matrix/blob/549595a06779a25e9fda132f1b430e8c5463028a/LicheePi4A/Fedora/README_zh.md?plain=1#L8
- https://github.com/ruyisdk/support-matrix/blob/549595a06779a25e9fda132f1b430e8c5463028a/M0s/FreeRTOS/README_zh.md?plain=1#L8

## Code & Logs

- https://github.com/ruyisdk/support-matrix/blob/549595a06779a25e9fda132f1b430e8c5463028a/Meles/RevyOS/README.md?plain=1#L35
- https://github.com/ruyisdk/support-matrix/blob/549595a06779a25e9fda132f1b430e8c5463028a/Meles/RevyOS/README_zh.md?plain=1#L35
- https://github.com/ruyisdk/support-matrix/blob/549595a06779a25e9fda132f1b430e8c5463028a/M0P_Dock/FreeRTOS/README_zh.md?plain=1#L108
- https://github.com/ruyisdk/support-matrix/blob/549595a06779a25e9fda132f1b430e8c5463028a/LicheeCluster4A/Fedora/README_zh.md?plain=1#L109
- https://github.com/ruyisdk/support-matrix/blob/549595a06779a25e9fda132f1b430e8c5463028a/M1s/BuildRoot/README.md?plain=1#L77
- https://github.com/ruyisdk/support-matrix/blob/549595a06779a25e9fda132f1b430e8c5463028a/LicheeConsole4A/RevyOS/README_zh.md?plain=1#L25
- https://github.com/ruyisdk/support-matrix/blob/549595a06779a25e9fda132f1b430e8c5463028a/LicheePi4A/ArchLinux/README.md?plain=1#L113
- https://github.com/ruyisdk/support-matrix/blob/549595a06779a25e9fda132f1b430e8c5463028a/LicheePi4A/ArchLinux/README_zh.md?plain=1#L116
- https://github.com/ruyisdk/support-matrix/blob/549595a06779a25e9fda132f1b430e8c5463028a/LicheeConsole4A/RevyOS/README.md?plain=1#L25
- https://github.com/ruyisdk/support-matrix/blob/549595a06779a25e9fda132f1b430e8c5463028a/M1s/BuildRoot/README_zh.md?plain=1#L77
- https://github.com/ruyisdk/support-matrix/blob/549595a06779a25e9fda132f1b430e8c5463028a/LicheePi4A/Fedora/README.md?plain=1#L8
- https://github.com/ruyisdk/support-matrix/blob/549595a06779a25e9fda132f1b430e8c5463028a/LicheePi4A/Armbian/README.md?plain=1#L96
- https://github.com/ruyisdk/support-matrix/blob/549595a06779a25e9fda132f1b430e8c5463028a/LicheePi4A/Armbian/README.md?plain=1#L96
- https://github.com/ruyisdk/support-matrix/blob/549595a06779a25e9fda132f1b430e8c5463028a/LicheePi4A/Armbian/README_zh.md?plain=1#L98
- https://github.com/ruyisdk/support-matrix/blob/549595a06779a25e9fda132f1b430e8c5463028a/M0P_Dock/FreeRTOS/README.md?plain=1#L13

**Comment by KevinMX** [comment]
We won't and we can't change those names in URLs, device trees, etc.
