### ISSUE TITLE
[Page Content] Duo S buildroot to 1.1.3

### ISSUE THREAD

**Issue by Arielfoever** [ruyisdk/support-matrix#78]
### Please Choose

- [ ] I'm working on fixing this issue.
- [X] I confirmed that there is no similar issue.

### I am visiting this page

https://github.com/ruyisdk/support-matrix/blob/main/Duo_S/BuildRoot/README.md

### I found new information here.

https://github.com/milkv-duo/duo-buildroot-sdk/releases

**Comment by Gekyume777** [comment]
done

**Comment by Arielfoever** [comment]
> done

pr and close it
