### ISSUE TITLE
[Page Content] Fedora on Duo S

### ISSUE THREAD

**Issue by Arielfoever** [ruyisdk/support-matrix#79]
### Please Choose

- [ ] I'm working on fixing this issue.
- [X] I confirmed that there is no similar issue.

### Product Name

Duo S

### CPU

XuanTie C906 + ARM Cortex-A53

### CPU Core

SG2000

### I found new information here.

https://mirror.iscas.ac.cn/fedora-riscv/dl/Milk-V/DuoS/images/latest/

**Comment by Gekyume777** [comment]
done
