### ISSUE TITLE
[Page Content] Nuttx Duo S

### ISSUE THREAD

**Issue by Arielfoever** [ruyisdk/support-matrix#80]
### Please Choose

- [ ] I'm working on fixing this issue.
- [X] I confirmed that there is no similar issue.

### I am visiting this page

https://github.com/ruyisdk/support-matrix/blob/main/Duo_S/NuttX/README.md

### I found new information here.

https://github.com/lupyuen/nuttx-sg2000

### Give out some notes.

Sophgo SG2000 is officially supported by NuttX Mainline! (Including Milk-V Duo S and Pine64 Oz64)

**Comment by Gekyume777** [comment]
pass-test
