### ISSUE TITLE
[Page Content] duo has 1.1.3 new buildroot

### ISSUE THREAD

**Issue by Arielfoever** [ruyisdk/support-matrix#86]
### Please Choose

- [ ] I'm working on fixing this issue.
- [X] I confirmed that there is no similar issue.

### I am visiting this page

https://github.com/ruyisdk/support-matrix/tree/main/Duo/BuildRoot

### I found new information here.

https://github.com/milkv-duo/duo-buildroot-sdk/releases/tag/v1.1.3

**Comment by Arielfoever** [comment]
https://github.com/ruyisdk/packages-index/issues/8 waiting

**Comment by KevinMX** [comment]
Done via https://github.com/ruyisdk/support-matrix/pull/98
